services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped

volumes:
  pgdata:
